[workspace]
resolver = "2"
members = [
    "crates/impulse-core",
    "crates/impulsed",
    "crates/impulse-connector",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/goidago/impulse-ring"

[workspace.dependencies]
libc = "0.2"
apache-avro = "0.17"
serde = { version = "1", features = ["derive"] }
getrandom = "0.2"
serde_bytes = "0.11"
sha2 = "0.10"
log = "0.4"
