[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/connector",
    "crates/impulsed",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
impulse-ring-core = { path = "crates/core" }
impulse-ring-connector = { path = "crates/connector" }

libc = "0.2"
apache-avro = "0.17"
serde = { version = "1", features = ["derive"] }
getrandom = "0.2"
serde_bytes = "0.11"
sha2 = "0.10"
log = "0.4"
