[package]
name = "impulsed"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "impulsed"
path = "src/lib.rs"

[[bin]]
name = "impulsed"
path = "src/main.rs"

[dependencies]
impulse-ring-core.workspace = true
libc.workspace = true
apache-avro.workspace = true
serde.workspace = true
getrandom.workspace = true
log = { workspace = true, features = ["std"] }

[dev-dependencies]
impulse-ring-connector.workspace = true
impulse-ring-core.workspace = true
serde.workspace = true
serde_bytes.workspace = true
